#- name: modify ssl crt
#  sudo: yes
#  copy:
#    src: ssl
#    dest: /etc/nginx
#    owner: root
#    group: root
#    mode: 0755

- name: modify nginx config
  template:
    src: nginx/ghost.conf
    dest: /etc/nginx/conf.d/ghost.conf
    owner: root
    group: root
    mode: 0644
  notify: restart nginx
